# Site
repository: abdulahad-92/abdulahad-92.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Abdul Ahad
title: Aspiring Full-Stack Web Developer
email: abdulahadchachar92@gmail.com
phone: +92-123-456-7890
website: https://abdulahad-92.github.io
website_title: Portfolio

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: abdulahad-92
linkedin_username: abdul-ahad-chachar-a7379b262

# Additional icon links
additional_links:
  - title: Email
    icon: fas fa-envelope
    url: mailto:abdulahadchachar92@gmail.com

# About Section
about_title: About Me
about_profile_image: images/profile.png
about_content: |
  Hi, I'm Abdul Ahad, an aspiring **Full-Stack Web Developer** from Pakistan, passionate about building innovative web applications. I’m self-taught, having honed my skills in the MERN stack (MongoDB, Express.js, React, Node.js) through courses on **Coursera**, **DataCamp**, and **YouTube**. I also work with data tools like **Power BI** and **Excel** to create insightful visualizations.

  I’m currently focused on developing new projects, such as a **Weather App** and a **Quiz App**, to sharpen my skills in JavaScript and React. Explore my work on [GitHub](https://github.com/abdulahad-92) and connect with me to collaborate on exciting ideas!

# Content Sections
content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Weather-App-18-Jan-2024
        link: https://github.com/abdulahad-92/Weather-App-18-Jan-2024
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92/Weather-App-18-Jan-2024
        quote: >
          A dynamic weather application built with JavaScript.
        description: |
          Created a responsive weather app using JavaScript and APIs to fetch real-time weather data, featuring a clean UI and accurate forecasts for users worldwide.
      - layout: left
        title: Quiz-App-15-Feb-2024
        link: https://github.com/abdulahad-92/Quiz-App-15-Feb-2024
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92/Quiz-App-15-Feb-2024
        quote: >
          An interactive quiz application using React.
        description: |
          Developed a quiz app with React, incorporating features like score tracking, timer, and dynamic question rendering, aimed at providing an engaging user experience.
      - layout: left
        title: Bliss-Airline-Web-Page
        link: https://github.com/abdulahad-92/Bliss-Airline-Web-Page
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92/Bliss-Airline-Web-Page
        quote: >
          A visually appealing airline webpage built with CSS.
        description: |
          Designed a responsive webpage for an airline, utilizing advanced CSS techniques to ensure cross-browser compatibility and a modern aesthetic.
      - layout: left
        title: Todo-list-May-24-2023
        link: https://github.com/abdulahad-92/Todo-list-May-24-2023
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92/Todo-list-May-24-2023
        quote: >
          A functional todo list application using JavaScript.
        description: |
          Built a dynamic todo list app with JavaScript, featuring task creation, deletion, and status tracking, with a focus on clean code and user experience.
      - layout: left
        title: Financier-10-Sep-2023
        link: https://github.com/abdulahad-92/Financier-10-Sep-2023
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92/Financier-10-Sep-2023
        quote: >
          A financial application built with JavaScript.
        description: |
          Developed a financial tracking tool using JavaScript, enabling users to manage budgets and transactions with a responsive interface.
  - title: Current Focus
    layout: list
    content:
      - layout: right
        title: Building New Projects
        sub_title: Self-Taught Developer
        caption: 2024 - Present
        quote: >
          Passionate about creating innovative web solutions.
        description: |
          Actively developing new projects to expand my portfolio, focusing on the MERN stack and data tools like Power BI and Excel. Currently working on applications like a Weather App and Quiz App to enhance my skills in JavaScript and React.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: IBA Karachi
        sub_title: BS in Economics
        caption: 2024 - Present
        quote: >
          Building a strong foundation in economics and technology.
        description: |
          Currently pursuing a BS in Economics at IBA Karachi, while self-teaching web development and data analysis through online platforms like **Coursera**, **DataCamp**, and **YouTube**. Gained proficiency in the MERN stack, Power BI, and Excel through structured courses and tutorials.
  - title: Skills
    layout: text
    content: |
      - **Front-end**: HTML, CSS, JavaScript, React, Bootstrap, Sass
      - **Back-end**: Node.js, Express.js, MongoDB
      - **Data Tools**: Power BI, Excel
      - **Other**: Python, Git
      - **Soft Skills**: Problem-solving, self-motivation, continuous learning

      I’ve developed these skills through dedicated learning on Coursera, DataCamp, and YouTube, with a focus on building practical, real-world projects.
  - title: Interests
    layout: text
    content: |
      I’m passionate about exploring new web technologies and tools, contributing to open-source projects on [GitHub](https://github.com/abdulahad-92), and solving coding challenges. I also enjoy mentoring aspiring developers and staying updated with industry trends to fuel my growth.

# Footer
footer_show_references: true
references_title: References Available Upon Request

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "lib/"
  - "scripts/"
  - "docker-compose.yml"
