# Site
repository: abdulahad-92/abdulahad-92.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Abdul Ahad
title: Full-Stack Web Developer
email: abdulahadchachar92@gmail.com
phone: +92-123-456-7890
website: https://abdulahad-92.github.io
website_title: Portfolio

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: abdulahad-92
linkedin_username: abdul-ahad-chachar-a7379b262

# Additional icon links
additional_links:
  - title: Email
    icon: fas fa-envelope
    url: mailto:abdulahadchachar92@gmail.com

# Google Analytics and Tag Manager (optional, disabled for simplicity)
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Hi, I'm Abdul Ahad, a passionate **Full-Stack Web Developer** from Pakistan with expertise in the MERN stack (MongoDB, Express.js, React, Node.js). I specialize in building responsive, scalable web applications and am currently working on an **Email Automation tool** to streamline workflows. My skills include front-end technologies like HTML, CSS, JavaScript, and React, as well as back-end development with Node.js and MongoDB. I also have experience with data tools like **Power BI** and **Excel**.

  I’m always learning, currently diving deeper into the MERN stack, and I thrive on solving complex problems through clean, efficient code. Check out my [GitHub](https://github.com/abdulahad-92) for my latest projects!

# Content Sections
content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Email Automation Tool
        link: https://github.com/abdulahad-92
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92
        quote: >
          A tool to automate email workflows using Node.js and MongoDB.
        description: |
          Developed a full-stack application to automate email sending processes, integrating Node.js for back-end logic, MongoDB for data storage, and React for a user-friendly interface. Focused on scalability and performance optimization.
      - layout: left
        title: Bliss-Airline-Web-Page
        link: https://github.com/abdulahad-92/Bliss-Airline-Web-Page
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92/Bliss-Airline-Web-Page
        quote: >
          A visually appealing airline webpage built with CSS.
        description: |
          Designed and implemented a responsive webpage for an airline, utilizing advanced CSS techniques to ensure cross-browser compatibility and a modern aesthetic.
      - layout: left
        title: Todo-list-May-24-2023
        link: https://github.com/abdulahad-92/Todo-list-May-24-2023
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92/Todo-list-May-24-2023
        quote: >
          A functional todo list application using JavaScript.
        description: |
          Built a dynamic todo list app with JavaScript, featuring task creation, deletion, and status tracking, with a focus on clean code and user experience.
      - layout: left
        title: Financier-10-Sep-2023
        link: https://github.com/abdulahad-92/Financier-10-Sep-2023
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92/Financier-10-Sep-2023
        quote: >
          A financial application built with JavaScript.
        description: |
          Developed a financial tracking tool using JavaScript, enabling users to manage budgets and transactions with a responsive interface.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Freelance Web Developer
        sub_title: Full-Stack Developer
        caption: January 2023 - Present
        quote: >
          Building innovative web solutions for clients.
        description: |
          Designed and developed multiple web applications, including an Email Automation tool, using the MERN stack. Collaborated with clients to deliver responsive, user-friendly interfaces and optimized back-end systems. Utilized Power BI and Excel for data visualization and analysis to support project requirements.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: University of Karachi
        sub_title: BS in Computer Science
        caption: 2018 - 2022
        quote: >
          Specialized in software development and database systems.
        description: |
          Completed coursework in web development, data structures, algorithms, and database management. Developed several projects using JavaScript, Python, and MongoDB, graduating with a strong foundation in full-stack development.
  - title: Skills
    layout: text
    content: |
      - **Front-end**: HTML, CSS, JavaScript, React, Bootstrap, Sass
      - **Back-end**: Node.js, Express.js, MongoDB
      - **Data Tools**: Power BI, Excel
      - **Other**: Python, Git
      - **Soft Skills**: Problem-solving, teamwork, communication, time management

      I’m proficient in building responsive web applications and analyzing data to drive insights, with a keen eye for detail and a passion for continuous learning.

  - title: Interests
    layout: text
    content: |
      Beyond coding, I’m passionate about contributing to open-source projects on [GitHub](https://github.com/abdulahad-92), exploring new web technologies, and staying updated with industry trends. I also enjoy solving coding challenges on platforms like LeetCode and mentoring aspiring developers in my community.

# Footer
footer_show_references: true
references_title: References Available Upon Request

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "lib/"
  - "scripts/"
  - "docker-compose.yml"
