# Site
repository: abdulahad-92/abdulahad-92.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Abdul Ahad
title: Aspiring Full-Stack Web Developer
email: abdulahadchachar92@gmail.com
phone: +92-123-456-7890
website: https://abdulahad-92.github.io
website_title: Portfolio

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: abdulahad-92
linkedin_username: abdul-ahad-chachar-a7379b262

# Additional icon links
additional_links:
  - title: Email
    icon: fas fa-envelope
    url: mailto:abdulahadchachar92@gmail.com

# Custom Styling
sass:
  sass_dir: _sass
  style: compressed
  custom:
    variables:
      primary-color: '#1E3A8A'  # Deep blue from suit
      accent-color: '#DC2626'   # Red from tie
      text-color: '#F9FAFB'

# SEO Configuration
plugins:
  - jekyll-seo-tag
seo:
  name: Abdul Ahad
  description: Portfolio of Abdul Ahad, an aspiring full-stack web developer skilled in MERN stack, Power BI, and Excel.
  author: Abdul Ahad
  twitter:
    username: abdulahad-92
  social:
    links:
      - https://github.com/abdulahad-92
      - https://linkedin.com/in/abdul-ahad-chachar-a7379b262

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  <div class="animated-fade">
    Hi, I'm Abdul Ahad, an aspiring **Full-Stack Web Developer** from Pakistan, passionate about crafting innovative web solutions. Self-taught through **Coursera**, **DataCamp**, and **YouTube**, I’ve mastered the MERN stack (MongoDB, Express.js, React, Node.js) and data tools like **Power BI** and **Excel**.
  </div>
  <blockquote>
    "I thrive on turning ideas into functional, beautiful applications."
  </blockquote>
  <p>Currently, I’m diving into projects like the **Email Automation Tool**. Check out my work on [GitHub](https://github.com/abdulahad-92)!</p>

# Content Sections
content:
  - title: Projects
    layout: list-grid
    content:
      - layout: left
        title: Email Automation Tool
        link: https://github.com/abdulahad-92
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92
        badge: Featured
        quote: >
          A tool to automate email workflows using Node.js and MongoDB.
        description: |
          Developed a full-stack application to automate email processes, integrating Node.js, MongoDB, and React for a scalable, user-friendly solution.
      - layout: left
        title: Quill-Hub
        link: https://github.com/abdulahad-92/Quill-Hub
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92/Quill-Hub
        quote: >
          A collaborative writing platform built with React.
        description: |
          Created a real-time collaborative writing tool with React, enabling seamless multi-user editing.
      - layout: left
        title: Marksheet Generator
        link: https://github.com/abdulahad-92/Marksheet-Generator
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92/Marksheet-Generator
        quote: >
          A tool to generate student marksheets using JavaScript.
        description: |
          Built a marksheet generator with JavaScript, allowing users to input grades and export formatted reports.
      - layout: left
        title: Todo-list-May-24-2023
        link: https://github.com/abdulahad-92/Todo-list-May-24-2023
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92/Todo-list-May-24-2023
        quote: >
          A functional todo list application using JavaScript.
        description: |
          Developed a dynamic todo list app with JavaScript, featuring task management and a clean UI.
      - layout: left
        title: Bliss-Airline-Web-Page
        link: https://github.com/abdulahad-92/Bliss-Airline-Web-Page
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92/Bliss-Airline-Web-Page
        quote: >
          A visually appealing airline webpage built with CSS.
        description: |
          Designed a responsive airline webpage using advanced CSS for a modern, cross-browser experience.
      - layout: left
        title: Financier-10-Sep-2023
        link: https://github.com/abdulahad-92/Financier-10-Sep-2023
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/abdulahad-92/Financier-10-Sep-2023
        quote: >
          A financial application built with JavaScript.
        description: |
          Created a financial tracking tool with JavaScript for budget and transaction management.
  - title: Current Focus
    layout: list
    content:
      - layout: right
        title: Building New Projects
        sub_title: Self-Taught Developer
        caption: 2024 - Present
        quote: >
          Passionate about creating innovative web solutions.
        description: |
          Actively developing projects like the Email Automation Tool, focusing on the MERN stack and data tools like Power BI and Excel to enhance my skills.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: IBA Karachi
        sub_title: BS in Economics
        caption: 2024 - Present
        quote: >
          Building a foundation in economics and technology.
        description: |
          Pursuing a BS in Economics at IBA Karachi, while self-teaching web development and data analysis via **Coursera**, **DataCamp**, and **YouTube**.
  - title: Skills
    layout: text
    content: |
      <div class="skill-badges">
        <span class="badge"><i class="fab fa-html5"></i> HTML</span>
        <span class="badge"><i class="fab fa-css3-alt"></i> CSS</span>
        <span class="badge"><i class="fab fa-js"></i> JavaScript</span>
        <span class="badge"><i class="fab fa-react"></i> React</span>
        <span class="badge"><i class="fab fa-node"></i> Node.js</span>
        <span class="badge"><i class="fas fa-database"></i> MongoDB</span>
        <span class="badge"><i class="fas fa-chart-bar"></i> Power BI</span>
        <span class="badge"><i class="fas fa-table"></i> Excel</span>
        <span class="badge"><i class="fab fa-python"></i> Python</span>
        <span class="badge"><i class="fab fa-git"></i> Git</span>
      </div>
      <p>Self-taught through Coursera, DataCamp, and YouTube, with a focus on practical project development.</p>
  - title: Interests
    layout: text
    content: |
      I love exploring new web technologies, contributing to open-source on [GitHub](https://github.com/abdulahad-92), and tackling coding challenges. I also enjoy mentoring others and staying ahead with industry trends.

# Call to Action
  - title: Get in Touch
    layout: text
    content: |
      <a href="https://github.com/abdulahad-92" class="btn">Explore My GitHub</a>
      Let’s collaborate on your next project!

# Footer
footer_show_references: true
references_title: References Available Upon Request
footer_content: |
  © 2025 Abdul Ahad. All rights reserved. | <a href="https://linkedin.com/in/abdul-ahad-chachar-a7379b262">Connect on LinkedIn</a>

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed
  custom:
    variables:
      primary-color: '#1E3A8A'
      accent-color: '#DC2626'
      text-color: '#F9FAFB'

plugins:
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "lib/"
  - "scripts/"
  - "docker-compose.yml"
